#!/bin/bash

# switch to environment JVM as needed
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

APACHE_EXECS_LIB=lib/org/apache/commons/commons-exec/1.2/commons-exec-1.2.jar
TOOL=lib/runtool-1.0.0-SNAPSHOT.jar

export JAVA_HOME=$JAVA_HOME
$JAVA_HOME/bin/java -cp $TOOL:$APACHE_EXECS_LIB  sbst.runtool.Main
